/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package wwworld;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class WwworldModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public WwworldModElements() {
		sounds.put(new ResourceLocation("wwworld", "yezhu"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "yezhu")));
		sounds.put(new ResourceLocation("wwworld", "shuiguihua"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "shuiguihua")));
		sounds.put(new ResourceLocation("wwworld", "danxiaodesongshu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "danxiaodesongshu")));
		sounds.put(new ResourceLocation("wwworld", "tengwanshengchengshi"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "tengwanshengchengshi")));
		sounds.put(new ResourceLocation("wwworld", "kuangleiwuyun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "kuangleiwuyun")));
		sounds.put(new ResourceLocation("wwworld", "bingshuangjitan"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "bingshuangjitan")));
		sounds.put(new ResourceLocation("wwworld", "qie"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "qie")));
		sounds.put(new ResourceLocation("wwworld", "nanguaguai"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "nanguaguai")));
		sounds.put(new ResourceLocation("wwworld", "dong"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "dong")));
		sounds.put(new ResourceLocation("wwworld", "yinghua"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "yinghua")));
		sounds.put(new ResourceLocation("wwworld", "chun"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "chun")));
		sounds.put(new ResourceLocation("wwworld", "xia"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "xia")));
		sounds.put(new ResourceLocation("wwworld", "qiu"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "qiu")));
		sounds.put(new ResourceLocation("wwworld", "diaoling"), new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "diaoling")));
		sounds.put(new ResourceLocation("wwworld", "fuxiuweiduchuansongmenyinxiao"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "fuxiuweiduchuansongmenyinxiao")));
		sounds.put(new ResourceLocation("wwworld", "tuboshujiajiao"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "tuboshujiajiao")));
		sounds.put(new ResourceLocation("wwworld", "tuboshuzhenjiao"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wwworld", "tuboshuzhenjiao")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("wwworld").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == WwworldModElements.ModElement.class)
						elements.add((WwworldModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(WwworldModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new WwworldModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		WwworldMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final WwworldModElements elements;
		protected final int sortid;

		public ModElement(WwworldModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
